---
name: auto-approve-pr

on:
  pull_request:
    types: [auto_merge_enabled, review_requested]

jobs:
  check-for-auto-approval:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      uses: ./.github/actions/auto_approval
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
