---
name: auto-approve-pr

on:
  pull_request:
    types: [review_requested]

jobs:
  check-for-auto-approval:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ./.github/actions/auto_approval
        with:
          token: ${{ secrets.GH_ACTIONS_PLAYGROUND_RW }}
          allowed_users: unknown, menny, yes_known
          review_for: anysoftkeyboard-bot
